
from blif_gen_random_graph_coloring import *
import os

def add_dnnf_main_model(blif_lines, u_num, c_num):

### I/O parameters
    blif_lines.append(f".model random{u_num}\n")
    blif_lines.append(".inputs ")
    blif_lines.extend([f"u{i} " for i in range(u_num)])
    blif_lines.extend([f"v{i} " for i in range(u_num)])
    blif_lines.extend([f"c{i} " for i in range(c_num)])
    blif_lines.extend([f"d{i} " for i in range(c_num)])
    blif_lines.append("\n")
    blif_lines.append(".outputs f\n")

### Graph subcircuit
    blif_lines.append(".subckt graph ")
    blif_lines.extend([f"U{i}=u{i} " for i in range(u_num)])
    blif_lines.extend([f"V{i}=v{i} " for i in range(u_num)])
    blif_lines.append("E=e1\n")

    blif_lines.append(".subckt graph ")
    blif_lines.extend([f"U{i}=v{i} " for i in range(u_num)])
    blif_lines.extend([f"V{i}=u{i} " for i in range(u_num)])
    blif_lines.append("E=e2\n")

    blif_lines.append(".subckt or2 I0=e1 I1=e2 O=e0\n")

### U, V not equal subcircuit
    blif_lines.append(f".subckt UneqV{u_num} ")
    blif_lines.extend([f"U{i}=u{i} " for i in range(u_num)])
    blif_lines.extend([f"V{i}=v{i} " for i in range(u_num)])
    blif_lines.append("O_equal=uvnotsame\n")

    blif_lines.append(".subckt and2 I0=e0 I1=uvnotsame O=e\n")

    blif_lines.append(".subckt not I=uvnotsame O=uvsame\n")

### Color not equal subcircuit
    blif_lines.extend([f".subckt UneqV{c_num} "])
    blif_lines.extend([f"U{i}=c{i} " for i in range(c_num)])
    blif_lines.extend([f"V{i}=d{i} " for i in range(c_num)])
    blif_lines.extend(["O_equal=colornotsame\n"])

    blif_lines.append(".subckt not I=colornotsame O=colorsame\n")

### Binary color subcircuit
    if c_num > 1:
        blif_lines.extend([".subckt fit_color_limit "] + [f"I{i}=c{i} " for i in range(c_num)] + ["G=clessthan\n"])
        blif_lines.extend([".subckt fit_color_limit "] + [f"I{i}=d{i} " for i in range(c_num)] + ["G=dlessthan\n"])
        blif_lines.extend([".subckt and2 I0=clessthan I1=dlessthan O=colorencode\n"])
    elif c_num == 1:
        blif_lines.append(".names colorencode\n1\n")
    else:
        print("Error: c_num should be at least 1")
        sys.exit(1)

### Main circuit
    blif_lines.append(".subckt imply I0=e I1=colornotsame O=phi1\n")

    blif_lines.append(".subckt imply I0=uvsame I1=colorsame O=phi2\n")

    blif_lines.append(".subckt and2 I0=phi1 I1=phi2 O=phi12\n")
    blif_lines.append(".subckt and2 I0=colorencode I1=phi12 O=f\n")

    blif_lines.append(".end\n\n")

def add_dnnf_implicit_graph(blif_lines, u_num, trial):
    graph_file = f"./dnnf_graphs/dnnf_graph_n{u_num}_{trial}.blif"
    with open(graph_file, "r") as f:
        graph_lines = f.readlines()
    blif_lines.extend(graph_lines)
    blif_lines.append("\n")
    return

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Generate blif file for random graph with coloring constraints.")
    parser.add_argument('-n', type=int, help='Number of nodes = 2^n (required)', required=True)
    parser.add_argument('-c', type=int, help='Colorability (required)', default=2)
    parser.add_argument('-t', type=int, help='Trial number (for random graph generation)', default=0)
    args = parser.parse_args()

    u_num = args.n
    colorability = args.c
    c_num = math.ceil(math.log2(colorability))
    trial = args.t

    # graph_file = f"./graphs/random_graph_n{u_num}_trial{trial}.csv"

    directory_name = 'dnnf_sample'

    try:
        os.mkdir(directory_name)
        print(f"Directory '{directory_name}' created.")
    except FileExistsError:
        print(f"Directory '{directory_name}' already exists.")
    except FileNotFoundError:
        print(f"Parent directory does not exist.")

    output_blif_file = f"./dnnf_sample/dnnf_graph_coloring_n{u_num}_c{colorability}_trial{trial}.blif"

    blif_lines = []

    # parse blif file generated by abc
    add_dnnf_main_model(blif_lines, u_num, c_num)

    # add_simple_implicit_graph(blif_lines, graph_file, u_num, output_graph_file)
    add_dnnf_implicit_graph(blif_lines, u_num, trial)
    
    if c_num > 1:
        add_fit_color_limit(blif_lines, colorability, c_num)
    add_subcircuit_model(blif_lines, u_num, c_num)
    
    print("\nWriting blif file...")
    with open(output_blif_file, "w") as f:
        f.writelines(blif_lines)
    print(f"Colorability: {colorability}")
    print("\nGenerate blif file successfully!\n")